"""ajustes finos na tabela de pedidos

Revision ID: 4512862dcf41
Revises: 857c9b7fee8a
Create Date: 2022-02-19 12:46:21.771492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4512862dcf41'
down_revision = '857c9b7fee8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_entrega', sa.String(), nullable=True))
        batch_op.drop_column('local_endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_endereco', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('local_entrega')

    # ### end Alembic commands ###
