"""ajustes finos na tabela de pedidos

Revision ID: 857c9b7fee8a
Revises: d0aca2a82773
Create Date: 2022-02-18 16:38:56.248707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857c9b7fee8a'
down_revision = 'd0aca2a82773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_entrega', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local_endereco', sa.String(), nullable=True))
        batch_op.drop_column('endereco')
        batch_op.drop_column('entrega')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('local_endereco')
        batch_op.drop_column('tipo_entrega')

    # ### end Alembic commands ###
