"""Nova coluna Senha

Revision ID: e4494b297386
Revises: d5675b12e299
Create Date: 2022-02-16 15:07:09.905825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4494b297386'
down_revision = 'd5675b12e299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
